/*
Copyright 2017 Ericsson AB.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

export const UPDATE_CLIENT = 'UPDATE_CLIENT'

export const AUTHENTICATE_CLIENT_STARTED = 'AUTHENTICATE_CLIENT_STARTED'
export const AUTHENTICATE_CLIENT_COMPLETE = 'AUTHENTICATE_CLIENT_COMPLETE'
export const AUTHENTICATE_CLIENT_FAILED = 'AUTHENTICATE_CLIENT_FAILED'

export const SET_STORED_DISPLAY_NAME = 'SET_STORED_DISPLAY_NAME'
export const UPDATE_DISPLAY_NAME_INPUT = 'UPDATE_DISPLAY_NAME_INPUT'
export const SET_DISPLAY_NAME_STARTED = 'SET_DISPLAY_NAME_STARTED'
export const SET_DISPLAY_NAME_COMPLETE = 'SET_DISPLAY_NAME_COMPLETE'
export const SET_DISPLAY_NAME_FAILED = 'SET_DISPLAY_NAME_FAILED'

export const UPDATE_CREATE_MEETING_NAME_INPUT = 'UPDATE_CREATE_MEETING_NAME_INPUT'
export const UPDATE_JOIN_MEETING_NAME_INPUT = 'UPDATE_JOIN_MEETING_NAME_INPUT'
export const MEETING_SETUP_STARTED = 'MEETING_SETUP_STARTED'
export const MEETING_SETUP_COMPLETE = 'MEETING_SETUP_COMPLETE'
export const MEETING_SETUP_FAILED = 'MEETING_SETUP_FAILED'
export const LEAVE_MEETING = 'LEAVE_MEETING'

export const LOAD_MEETING_LIST = 'LOAD_MEETING_LIST'
export const SORT_MEETING_LIST = 'SORT_MEETING_LIST'
export const REMOVE_MEETING_FROM_LIST = 'REMOVE_MEETING_FROM_LIST'

export const BEFORE_UNLOAD = 'BEFORE_UNLOAD'

export const ACQUIRE_MEETING_MEDIA_STARTED = 'ACQUIRE_MEETING_MEDIA_STARTED'
export const ACQUIRE_MEETING_MEDIA_COMPLETE = 'ACQUIRE_MEETING_MEDIA_COMPLETE'
export const ACQUIRE_MEETING_MEDIA_FAILED = 'ACQUIRE_MEETING_MEDIA_FAILED'

export const ROOM_MEMBER_PRESENCE_CHANGES = 'ROOM_MEMBER_PRESENCE_CHANGES'

export const CONFERENCE_CONNECTION_STATE = 'CONFERENCE_CONNECTION_STATE'
export const CONFERENCE_CONNECTION_ERROR = 'CONFERENCE_CONNECTION_ERROR'
export const CONFERENCE_PEER_UPSERT = 'CONFERENCE_PEER_UPSERT'
export const CONFERENCE_PEER_REMOVED = 'CONFERENCE_PEER_REMOVED'
export const CONFERENCE_SPEAKER_CHANGED = 'CONFERENCE_SPEAKER_CHANGED'
export const CONFERENCE_PEER_AUDIO_ADDED = 'CONFERENCE_PEER_AUDIO_ADDED'
export const CONFERENCE_PEER_AUDIO_REMOVED = 'CONFERENCE_PEER_AUDIO_REMOVED'
export const CONFERENCE_THUMBNAILS_ADDED = 'CONFERENCE_THUMBNAILS_ADDED'
export const CONFERENCE_THUMBNAILS_REMOVED = 'CONFERENCE_THUMBNAILS_REMOVED'
export const USER_AGENT_SHARE_UPDATE = 'USER_AGENT_SHARE_UPDATE'
export const MUTE_STATE_SHARE_UPDATE = 'MUTE_STATE_SHARE_UPDATE'

export const MEDIA_TOGGLE_MUTE = 'MEDIA_TOGGLE_MUTE'
export const MEDIA_TOGGLE_PEER_MUTE = 'MEDIA_TOGGLE_PEER_MUTE'

export const DEVTOOLS_TOGGLE_VISUALIZATION = 'DEVTOOLS_TOGGLE_VISUALIZATION'
