/*
Copyright 2016 Ericsson AB.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

export const adjectives = [
  'cool',
  'hip',
  'awesome',
  'adorable',
  'soft',
  'sick',
  'manly',
  'squeaky',
  'sad',
  'happy',
  'strong',
  'weak',
  'juggling',
  'fuzzy',
  'dangerous',
  'blind',
  'mute',
  'laughing',
  'crying',
  'loud',
  'quiet',
  'white',
  'yellow',
  'red',
  'blue',
  'green',
  'pink',
  'orange',
  'purple',
  'black',
  'beautiful',
  'clean',
  'elegant',
  'fancy',
  'handsome',
  'sparkling',
  'brave',
  'jolly',
  'delightful',
  'nice',
  'angry',
  'grumpy',
  'jealous',
  'lazy',
  'scary',
  'worried',
  'big',
  'colossal',
  'giant',
  'massive',
  'tiny',
]

export const nouns = [
  'man',
  'woman',
  'baby',
  'father',
  'mother',
  'dog',
  'cat',
  'bird',
  'hamster',
  'horse',
  'cow',
  'goat',
  'pig',
  'chicken',
  'oyster',
  'sheep',
  'whale',
  'penguin',
  'polarbear',
  'bear',
  'gazelle',
  'antilope',
  'elephant',
  'tiger',
  'lion',
  'hyena',
  'leopard',
  'gorilla',
  'monkey',
  'chimp',
  'bull',
  'ant',
  'fox',
  'hare',
  'wolf',
  'armadillo',
  'bison',
  'beetle',
  'owl',
  'chipmunk',
  'donkey',
  'dolphin',
  'duck',
  'camel',
  'badger',
  'butterfly',
  'crab',
  'crow',
  'alligator',
  'crocodile',
]

export const nouner = [
  'farmer',
  'manager',
  'hoarder',
  'investor',
  'ambassador',
  'collector',
  'educator',
  'maker',
  'administrator',
  'looter',
  'seller',
  'helper',
  'translator',
  'conspirator',
  'vendor',
  'constructor',
  'processor',
  'inventor',
  'engineer',
  'captor',
  'jailor',
  'oppressor',
  'surveyor',
  'operator',
  'commentator',
  'navigator',
  'inspector',
  'protector',
  'actor',
  'aviator',
]
